### PR TITLE
Remove the Suspense boundary for individual items

### PR DESCRIPTION
**Pull request by shuding**
As mentioned in https://github.com/vercel/next-rsc-demo/issues/13#issuecomment-988319153, we think removing the spinners for individual items will reduce layout shift and improve the overall experience of this app.

### CODE REVIEW

**Comment by gaearon** [comment]
When I tried this locally I got weird hydration errors. Is that specific to me?

**Comment by shuding** [comment]
Not specific to you, that's something we are looking into — reverting to a previous Next.js release should fix it (#14).

**Comment by vercel-team** [comment]
#### 📝 Changed routes:


| [**/rsc.server**](https://next-rsc-demo-80bg8t89h.vercel.sh/rsc.server) |
|:-:|
|<a href="https://next-rsc-demo-80bg8t89h.vercel.sh/rsc.server">Screenshot of /rsc.server</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/e26EFuLeebm1RBIpXHDbYjOsFsjJiPYBn-dvOHD8gpQHfp9Tm4e9aYFxGJcMwLbLEZB_GeF4p4-0bXQwE6ngrA.png">(view full size)</a> |







Commit ffa69f6f7c3e804d7e4448f66825796413e715a5 (https://next-rsc-demo-80bg8t89h.vercel.sh).

**Comment by gaearon** [comment]
Should we also fix up the parent suspense boundary to be more natural than a spinner? For example by giving body min height and then making the fallback empty, or something.

**Comment by shuding** [comment]
Good call, min div height with some skeletons inside (that matches the item height) will be better.

**Comment by shuding** [comment]
Updated now, with animating skeletons: https://next-rsc-demo-git-shu-0653.vercel.sh/rsc. Should be good for now I think.

**Comment by gaearon** [comment]
Can we make is to that the height of the skeleton is the same as the height of the content? Do we not know the number of the rows or the size of each?

**Review by gaearon — APPROVED** [review]
shipit

**Comment by shuding** [comment]
❤️

**Comment by gaearon** [comment]
Sometimes when I refresh I get this:

Screenshot 2021-12-08 at 00 23 51
Screenshot 2021-12-08 at 00 23 35

But not every time.

**Comment by gaearon** [comment]
When it's broken, I can see the scripts on the right are missing from the HTML:

Screenshot 2021-12-08 at 00 30 28

**Pull request merged**
